<?xml version="1.0"?> 
<robot name="glide" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>

  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>


  <xacro:property name="body_width" value="0.2" /> <!-- 8" ~= 0.2 m -->
  <xacro:property name="body_length" value="0.3" /> <!-- 12" ~= 0.3 m -->
  <xacro:property name="body_height" value="0.1" /> <!-- 4" ~= 0.1 m -->
  <xacro:property name="body_center" value="0.1" /> <!-- 4" ~= 0.1 m -->

  <xacro:property name="wheel_width" value="0.003" /> <!-- 1/8" ~= 0.003 m -->
  <xacro:property name="wheel_radius" value="0.077" /> <!-- 3 1/16" ~= 0.077 m -->
  <xacro:property name="wheel_gap" value="0.03175" /> <!-- 1 1/4" ~= 0.03175 m -->
  <xacro:property name="wheel_offset" value="0.0381" /> <!-- 1 5" ~= 0.0381 m -->

  <xacro:property name="bar_radius" value="0.003" /> <!-- 1/8" ~= 0.003 m -->
  <xacro:property name="bar_length" value="${2*wheel_gap + body_width}" /> <!-- 1 1/4" ~= 0.03175 m -->

  <xacro:property name="degrees_45" value="${45 * pi/180}"/>
  <xacro:property name="degrees_90" value="${90 * pi/180}"/>
  <xacro:property name="degrees_55" value="${55 * pi/180}"/>

  <xacro:macro name="bar" params="name x_offset z_offset parent_link">
    <link name="${name}_bar_link">
      <visual>
        <geometry>
          <cylinder length="${bar_length}" radius="${bar_radius}"/>
        </geometry>
        <origin rpy="${degrees_90} 0 0" xyz="0 0 0"/>
        <material name="white"/>
      </visual>
      <collision> 
        <origin rpy="${degrees_90} 0 0" xyz="0 0 0"/>
        <geometry> 
          <cylinder length="${bar_length}" radius="${bar_radius}"/>
        </geometry> 
      </collision>
    </link>
    <gazebo reference="${name}_bar_link">
      <material>Gazebo/White</material>
    </gazebo>

    <joint name="${name}_bar_joint" type="revolute">
      <limit lower="-0.2" upper="0.2" effort="100" velocity="3"/>
      <origin rpy="0 0 0" xyz="${x_offset} 0 ${z_offset}"/>
      <parent link="${parent_link}"/>
      <child link="${name}_bar_link"/>
      <axis xyz="0 0 1"/>
    </joint>
  </xacro:macro>

  <xacro:macro name="steer_wheel" params="name offset xy_reflect">
    <link name="front_${name}_wheel">
      <visual>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <material name="white"/>
      </visual>
      <collision> 
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry> 
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry> 
      </collision>
      <inertial> 
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <mass value="5.0"/> 
        <!--<cylinder_inertia m="0.2" r="0.3" h="0.1"/> -->
        <!-- <cylinder_inirtia m="${mass}" r="${radius}" h="${width}" /> -->
        <inertia ixx="7.90866056" ixy="0.00000006" ixz="0" iyy="7.90866056" iyz="0" izz="2.48398783"/>
	    </inertial> 
    </link>
    <gazebo reference="$front_{name}_wheel">
      <material>Gazebo/White</material>
    </gazebo>

    <joint name="front_${name}_wheel_joint" type="revolute">
      <limit lower="-0.9" upper="0.9" effort="100" velocity="1"/>
      <origin rpy="${degrees_90} 0 ${pi}" xyz="${offset + wheel_offset} ${xy_reflect * (wheel_gap + body_width/2)} ${wheel_radius}"/>
      <parent link="base_link"/>
      <child link="front_${name}_wheel"/>
      <axis xyz="0 1 0"/>
      <axis2 xyz="0 0 1"/>
    </joint>
  </xacro:macro>

  <xacro:macro name="rotate_wheel" params="name offset xy_reflect">
    <link name="rear_${name}_wheel">
      <visual>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <material name="white"/>
      </visual>
      <collision> 
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry> 
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry> 
      </collision>
      <inertial> 
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <mass value="5.0"/> 
        <!--<cylinder_inertia m="0.2" r="0.3" h="0.1"/> -->
        <!-- <cylinder_inirtia m="${mass}" r="${radius}" h="${width}" /> -->
        <inertia ixx="7.90866056" ixy="0.00000006" ixz="0" iyy="7.90866056" iyz="0" izz="2.48398783"/>
      </inertial> 
    </link>
    <joint name="rear_${name}_wheel_joint" type="continuous">
      <origin rpy="${degrees_90} 0 ${pi}" xyz="-0.5 ${xy_reflect * (wheel_gap + body_width/2)} ${wheel_radius}"/>
      <parent link="base_link"/>
      <child link="rear_${name}_wheel"/>
      <axis xyz="0 0 1"/>
    </joint>
  </xacro:macro>

  <!-- <link name="steer_bar_link">
      <visual>
        <geometry>
          <cylinder length="0.4" radius="${bar_radius}"/>
        </geometry>
        <origin rpy="${degrees_45} -${degrees_45} -${degrees_55}" xyz="0 0 0"/>
        <material name="white"/>
      </visual>
      <collision> 
        <origin rpy="${degrees_45} 0 0" xyz="0 0 0"/>
        <geometry> 
          <cylinder length="0.4" radius="${bar_radius}"/>
        </geometry> 
      </collision>
  </link>
  <joint name="steer_bar_joint" type="revolute">
    <limit lower="-0.2" upper="0.2" effort="100" velocity="0.1"/>
      <origin rpy="0 0 0" xyz="-${1.8*body_width} 0 ${body_length/1.1}"/>
      <parent link="base_link"/>
      <child link="steer_bar_link"/>
      <axis xyz="0 1 0"/>
    </joint> -->
  

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${body_center}"/>
      <material name="blue"/>
    </visual>
  </link>
  <gazebo reference="base_link">
      <material>Gazebo/Blue</material>
  </gazebo>

  <!-- <xacro:bar name="front" x_offset="${1.25*body_width}" z_offset="-${body_width}" parent_link="steer_bar_link"/> -->
  <xacro:steer_wheel name="right" offset="-0.1" xy_reflect="-1"/>
  <xacro:steer_wheel name="left" offset="-0.1" xy_reflect="1"/>
  <!-- <xacro:rotate_wheel name="front_right" offset="-0.1" xy_reflect="-1" /> -->
  <!-- <xacro:rotate_wheel name="front_left" offset="-0.1" xy_reflect="1" /> -->
  <!-- <xacro:bar name="rear" x_offset="-0.5" z_offset="${wheel_radius}" parent_link="base_link"/> -->
  <!-- <xacro:steer_wheel name="rear_right" offset="0" xy_reflect="-1" parent="rear_bar_link" /> -->
  <!-- <xacro:steer_wheel name="rear_left" offset="0" xy_reflect="1" parent="rear_bar_link"/> -->
  <xacro:rotate_wheel name="right" offset="-0.1" xy_reflect="-1" />
  <xacro:rotate_wheel name="left" offset="-0.1" xy_reflect="1" />
<link name="camera_bottom_screw_frame">
    <visual>
      <geometry>
          <box size="0.02505 0.090 0.025"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
          <box size="0.02505 0.090 0.025"/>
      </geometry>
    </collision>
  </link>

  <link name="camera_link"></link>

  <link name="camera_depth_frame"></link>

  <link name="camera_depth_optical_frame"></link>

  <link name="camera_color_frame"></link>

  <link name="camera_color_optical_frame"></link>

  <link name="camera_left_ir_frame"></link>

  <link name="camera_left_ir_optical_frame"></link>

  <link name="camera_right_ir_frame"></link>

  <link name="camera_right_ir_optical_frame"></link>


   <joint name="camera_joint" type="fixed">
    <parent link="base_link" />
    <child link="camera_bottom_screw_frame" />
    <pose xyz="0.4 0 0.25" rpy="0 0 0" />
  </joint>

  <joint name="camera_link_joint" type="fixed">
    <parent link="camera_bottom_screw_frame" />
    <child link="camera_link" />
    <pose xyz="0 0.0175 0.0125 " rpy="0 0 0" />
  </joint>

  <joint name="camera_depth_joint" type="fixed">
    <parent link="camera_link" />
    <child link="camera_depth_frame" />
    <pose xyz="0 0 0" rpy="0 0 0" />
  </joint>

  <joint name="camera_depth_optical_joint" type="fixed">
    <parent link="camera_depth_frame" />
    <child link="camera_depth_optical_frame" />
    <pose xyz="0 0 0 " rpy="-1.57 0 -1.57" />
  </joint>

  <joint name="camera_color_joint" type="fixed">
    <parent link="camera_depth_frame" />
    <child link="camera_color_frame" />
    <pose xyz="0 0 0" rpy="0 0 0" />
  </joint>

  <joint name="camera_color_optical_joint" type="fixed">
    <parent link="camera_color_frame" />
    <child link="camera_color_optical_frame" />
    <pose xyz="0 0 0 " rpy="-1.57 0 -1.57" />
  </joint>

  <joint name="camera_left_ir_joint" type="fixed">
    <parent link="camera_depth_frame" />
    <child link="camera_left_ir_frame" />
    <pose xyz="0 0 0 " rpy="0 0 0 " />
  </joint>

  <joint name="camera_left_ir_optical_joint" type="fixed">
    <parent link="camera_left_ir_frame" />
    <child link="camera_left_ir_optical_frame" />
    <pose xyz="0 0 0 " rpy="-1.57 0 -1.57" />
  </joint>

  <joint name="camera_right_ir_joint" type="fixed">
    <parent link="camera_depth_frame" />
    <child link="camera_right_ir_frame" />
    <pose xyz="0 -0.050 0 " rpy="0 0 0" />
  </joint>

  <joint name="camera_right_ir_optical_joint" type="fixed">
    <parent link="camera_right_ir_frame" />
    <child link="camera_right_ir_optical_frame" />
    <pose xyz="0 0 0 " rpy="-1.57 0 -1.57" />
  </joint>

  <link name="human_link">
    <visual>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
      <material name="blue"/>
    </visual>
  </link>
  <joint name="base_to_human" type="fixed">
    <origin rpy="0 ${degrees_90} 0" xyz="-0.5 0.0 ${2*body_center}"/>
    <parent link="base_link"/>
    <child link="human_link"/>
  </joint>

</robot> 