
#ifndef DEPTHIMAGETOLASERSCANROS_EXPORT_H
#define DEPTHIMAGETOLASERSCANROS_EXPORT_H

#ifdef DEPTHIMAGETOLASERSCANROS_STATIC_DEFINE
#  define DEPTHIMAGETOLASERSCANROS_EXPORT
#  define DEPTHIMAGETOLASERSCANROS_NO_EXPORT
#else
#  ifndef DEPTHIMAGETOLASERSCANROS_EXPORT
#    ifdef DepthImageToLaserScanROS_EXPORTS
        /* We are building this library */
#      define DEPTHIMAGETOLASERSCANROS_EXPORT __attribute__((visibility("default")))
#    else
        /* We are using this library */
#      define DEPTHIMAGETOLASERSCANROS_EXPORT __attribute__((visibility("default")))
#    endif
#  endif

#  ifndef DEPTHIMAGETOLASERSCANROS_NO_EXPORT
#    define DEPTHIMAGETOLASERSCANROS_NO_EXPORT __attribute__((visibility("hidden")))
#  endif
#endif

#ifndef DEPTHIMAGETOLASERSCANROS_DEPRECATED
#  define DEPTHIMAGETOLASERSCANROS_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef DEPTHIMAGETOLASERSCANROS_DEPRECATED_EXPORT
#  define DEPTHIMAGETOLASERSCANROS_DEPRECATED_EXPORT DEPTHIMAGETOLASERSCANROS_EXPORT DEPTHIMAGETOLASERSCANROS_DEPRECATED
#endif

#ifndef DEPTHIMAGETOLASERSCANROS_DEPRECATED_NO_EXPORT
#  define DEPTHIMAGETOLASERSCANROS_DEPRECATED_NO_EXPORT DEPTHIMAGETOLASERSCANROS_NO_EXPORT DEPTHIMAGETOLASERSCANROS_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef DEPTHIMAGETOLASERSCANROS_NO_DEPRECATED
#    define DEPTHIMAGETOLASERSCANROS_NO_DEPRECATED
#  endif
#endif

#endif /* DEPTHIMAGETOLASERSCANROS_EXPORT_H */
