
#ifndef DEPTHIMAGETOLASERSCAN_EXPORT_H
#define DEPTHIMAGETOLASERSCAN_EXPORT_H

#ifdef DEPTHIMAGETOLASERSCAN_STATIC_DEFINE
#  define DEPTHIMAGETOLASERSCAN_EXPORT
#  define DEPTHIMAGETOLASERSCAN_NO_EXPORT
#else
#  ifndef DEPTHIMAGETOLASERSCAN_EXPORT
#    ifdef DepthImageToLaserScan_EXPORTS
        /* We are building this library */
#      define DEPTHIMAGETOLASERSCAN_EXPORT __attribute__((visibility("default")))
#    else
        /* We are using this library */
#      define DEPTHIMAGETOLASERSCAN_EXPORT __attribute__((visibility("default")))
#    endif
#  endif

#  ifndef DEPTHIMAGETOLASERSCAN_NO_EXPORT
#    define DEPTHIMAGETOLASERSCAN_NO_EXPORT __attribute__((visibility("hidden")))
#  endif
#endif

#ifndef DEPTHIMAGETOLASERSCAN_DEPRECATED
#  define DEPTHIMAGETOLASERSCAN_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef DEPTHIMAGETOLASERSCAN_DEPRECATED_EXPORT
#  define DEPTHIMAGETOLASERSCAN_DEPRECATED_EXPORT DEPTHIMAGETOLASERSCAN_EXPORT DEPTHIMAGETOLASERSCAN_DEPRECATED
#endif

#ifndef DEPTHIMAGETOLASERSCAN_DEPRECATED_NO_EXPORT
#  define DEPTHIMAGETOLASERSCAN_DEPRECATED_NO_EXPORT DEPTHIMAGETOLASERSCAN_NO_EXPORT DEPTHIMAGETOLASERSCAN_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef DEPTHIMAGETOLASERSCAN_NO_DEPRECATED
#    define DEPTHIMAGETOLASERSCAN_NO_DEPRECATED
#  endif
#endif

#endif /* DEPTHIMAGETOLASERSCAN_EXPORT_H */
